name: Test & Release

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: wapc/wasmtime-provider/.github/workflows/tests.yml@master

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: cargo publish
        run: cargo publish --no-verify
